### PR TITLE
feat: Update Appwrite package to v8.1.0 to add support for Appwrite v1

### LINKED ISSUE #4259: 🪄 Upgrade ’demo-quiz-with-flutter’ to Appwrite 1.0
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-quiz-with-flutter** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-quiz-with-flutter to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-quiz-with-flutter**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR do?
Add support for Appwrite v1 (Dart package version: v8.1.0 (latest))

## Test Plan
Updated the code to make it work with the new dependency changes.

Tried out on Android 10

## Related PRs and Issues
Closes https://github.com/appwrite/appwrite/issues/4259

### Have you read the Contributing Guidelines on issues
Yes

### CODE REVIEW

**Comment by gewenyu99** [comment]
The changes themselves look good, I'm gonna try to run this quickly to see if it's working 💯

**Comment by gewenyu99** [comment]
@VoidCupboard It'll be great to see some screen caps on devices, so I can be sure they're working fine as well.

Great job 💯

**Comment by VoidCupboard** [comment]
Thanks a bunch, @gewenyu99 :)

Here is the video showing the demo on a Physical Device (Android 10):

https://user-images.githubusercontent.com/82395440/194702767-3cc437b9-77fb-469b-b7d0-7c375a6741dd.mp4

**Review by gewenyu99 — APPROVED** [review]
These changes look good now!

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
